spring:
  application:
    name: video-osd-simulator-v1

server:
  port: 18083

simulator:
  osd:
    enabled: true
    websocket-path: /ws/osd
    frame-hfov-deg: 60.0
    frame-vfov-deg: 40.0
    ws-sender-threads: 4
    ws-drop-log-interval-millis: 5000
    ws-send-slow-threshold-millis: 1000
    ws-crypto:
      enabled: true
      mode: aes-gcm
      key-base64: MDEyMzQ1Njc4OWFiY2RlZg==
      key-id: relay-key-01
    mqtt:
      broker-url: tcp://192.168.1.112:1883
      client-id: video-osd-simulator-v1
      topic: thing/product/8UUXN4E00A05F5/drc/up
      username:
      password:
      qos: 0
      auto-reconnect: true
      clean-session: true
      direct-consume-enabled: true

#star:
#  license:
#    code: "StZq89/gkMTE/wR/NEF2jhLR2kAvQeLaqcDA7+/4//MeASYQntHj43ID2AjdR8jbCFyoThNnPomy4bhiHxW2xPQZq9wW3GJ+KSbDYmj51djOHsfbwPsB+EEio8ayHIFMuBQXy7FJnb443+GtpRCphvBFh5saqULISNe1HMaJRr1cyKv71v60MW5Yfk/iLj78"