server:
  port: 18083

spring:
  application:
    name: video-osd-simulator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xm_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Win@2026!
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

simulator:
  ffmpeg:
    path: "C:/Users/44527/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1.1-full_build/bin/ffmpeg.exe"
    input-patterns: "*.mp4,*.flv,*.mov,*.mkv"
  osd:
    source-type: MYSQL
    publish-time-start: 2026-07-01T00:00:00
    publish-time-end: 2026-07-01T23:59:59
    require-task-id-match: false
    frame-hfov-deg: 60.0
    frame-vfov-deg: 40.0
    mqtt:
      broker-url: tcp://127.0.0.1:1883
      client-id: video-osd-simulator
      topic: thing/product/8UUXN4E00A05F5/drc/up
      username:
      password:
      qos: 0
      auto-reconnect: true
      clean-session: true
#  osd:
#    source-type: STATIC_JSON
#    websocket-endpoint: ws://127.0.0.1:18083/ws/osd
#    static-json-location: classpath:/static/long_text_1813A2F3-3BCF-47A1-BE25-B6A7C4F3E1D8.json
#    fixed-interval-millis: 1000
#    require-task-id-match: false
#    publish-time-start:
#    publish-time-end:
#    frame-hfov-deg: 60.0
#    frame-vfov-deg: 40.0
  video:
    source-directory: ./sample-videos
    source-file:
  zlm:
    host: 127.0.0.1
    http-port: 8086
    rtmp-port: 7935
    rtsp-port: 8554
    rtc-port: 10000
    app: live
    stream: drone001
  webrtc:
    push-command-template: webrtc-pusher --input "{videoFile}" --host {zlmHost} --app {app} --stream {stream}
