spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xm_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Win@2026!
  sql:
    init:
      mode: never

simulator:
  osd:
    publish-time-start:
    publish-time-end:
    websocket-endpoint: ws://127.0.0.1:18083/osd
  zlm:
    host: 127.0.0.1
    rtmp-port: 7935
    rtsp-port: 8554
    rtc-port: 10000
    app: live
    stream: drone001
  video:
    source-file: C:/Users/44527/Downloads/trailer_video_test.mp4
